USE [AndroidBasico]
GO

INSERT INTO [dbo].[Filmes] ([Titulo],[Resumo],[Estrelas]) VALUES ('Star Wars I','Guerra de Naves no espaço',5)
INSERT INTO [dbo].[Filmes] ([Titulo],[Resumo],[Estrelas]) VALUES ('Guia dos Mochileiro das Galaxias','Tudo sobre o mundo nerd',5)
INSERT INTO [dbo].[Filmes] ([Titulo],[Resumo],[Estrelas]) VALUES ('Star Wars II','Continuação da Guerra de Naves no espaço',4)
INSERT INTO [dbo].[Filmes] ([Titulo],[Resumo],[Estrelas]) VALUES ('Star Wars III','Continuação da Guerra de Naves no espaço',3)
GO

