USE [AndroidBasico]
GO

INSERT INTO [dbo].[Filmes_Atores] ([ID_Filme],[ID_Ator]) VALUES (1,1)
INSERT INTO [dbo].[Filmes_Atores] ([ID_Filme],[ID_Ator]) VALUES (1,2)
INSERT INTO [dbo].[Filmes_Atores] ([ID_Filme],[ID_Ator]) VALUES (1,3)
INSERT INTO [dbo].[Filmes_Atores] ([ID_Filme],[ID_Ator]) VALUES (1,4)
GO

INSERT INTO [dbo].[Filmes_Atores] ([ID_Filme],[ID_Ator]) VALUES (2,1)
INSERT INTO [dbo].[Filmes_Atores] ([ID_Filme],[ID_Ator]) VALUES (2,4)

INSERT INTO [dbo].[Filmes_Atores] ([ID_Filme],[ID_Ator]) VALUES (3,1)
INSERT INTO [dbo].[Filmes_Atores] ([ID_Filme],[ID_Ator]) VALUES (3,2)


INSERT INTO [dbo].[Filmes_Atores] ([ID_Filme],[ID_Ator]) VALUES (4,2)
INSERT INTO [dbo].[Filmes_Atores] ([ID_Filme],[ID_Ator]) VALUES (4,3)
INSERT INTO [dbo].[Filmes_Atores] ([ID_Filme],[ID_Ator]) VALUES (4,4)

